name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Sesuaikan dengan nama cabang utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Mengatur Konfigurasi Git
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"

      - name: Buat Branch gh-pages Jika Belum Ada
        run: |
          git checkout -b gh-pages

      # ...

      - name: Deploy to GitHub Pages
        run: |
          git clean -fxd
          cp -r build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages

      # ...
